os: linux
dist: focal
language: python

python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev

jobs:
  allow_failures:
    - python: 3.9-dev

install:
  - pip install codecov flake8 -r requirements.txt -r test-requirements.txt

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - pytest --cov=autodeploy --cov-report term-missing

after_success:
  - codecov
