language: python

os:
    - linux

python:
    - 2.7
    - 3.5
    - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codecov

script:
  - pytest --cov=autodeploy --cov-report term-missing

after_success:
  - codecov
